version: '3'
services:
# Database Service (Mysql)
  database:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - 3307:3306
    volumes:
      - /home/mysql/data
    networks:
      - backend
 # App backend service
  spring-boot:
    depends_on:
      - database
    container_name: springcontainer
    image: salimbhk/achat:65
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://192.168.1.184:3307/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - /home/m2
    stdin_open: true
    tty: true
    networks:
      - backend
    restart: on-failure
  
networks:
  backend:
    
